// Generalized Payload for ../event/MolocoEvent
// This payload is a generalization of all the possible payloads
// that will be auto-generated from the ./bin/run generate:types command
// (https://github.com/segmentio/action-destinations/tree/main?tab=readme-ov-file#actions-cli).
export interface EventPayload {
  /**
   * Unique ID generated by the client to suppress duplicate events. The length should not exceed 128 characters.
   */
  event_id: string
  /**
   * Timestamp that the event happened at.
   */
  timestamp: string | number
  /**
   * User Identifier for the platform. The length should not exceed 128 characters.
   */
  user_id: string
  /**
   * Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.
   */
  session_id?: string
  /**
   * Resolved Bid Id given by Topsort Source
   */
  resolved_bid_id: string
}

export interface PurchasePayload {
  /**
   * Unique ID generated by the client to suppress duplicate events. The length should not exceed 128 characters.
   */
  event_id: string
  /**
   * Timestamp that the event happened at.
   */
  timestamp: string | number
  /**
   * User Identifier for the platform. The length should not exceed 128 characters.
   */
  user_id: string
  /**
   * Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.
   */
  session_id?: string
  /**
   * Purchase amount
   */
  items: ItemPayload[]
}

// Generalized payload for ../fields/createItemInputField, note that it is not an array type
export interface ItemPayload {
  /**
   * Unique identifier of the Item.
   */
  id: string
  /**
   * Monetary amount without currency. (e.g., 12.34 for $12.34 if currency is "USD") required if currency is provided
   */
  price?: number
  /**
   * Currency information, required if price is provided
   */
  currency?: string
  /**
   * Quantity of the item. Recommended.
   */
  quantity?: number
  /**
   * Unique identifier of the Seller.
   */
  seller_id?: string
}
