import { InputField } from '@segment/actions-core/destination-kit/types'

export const event_id: InputField = {
  label: 'Event ID',
  description:
    'Unique ID generated by the client to suppress duplicate events. The length should not exceed 128 characters.',
  type: 'string',
  required: false,
  default: {
    '@path': '$.messageId'
  }
}

export const timestamp: InputField = {
  label: 'Timestamp',
  description: 'Timestamp that the event happened at.',
  type: 'datetime',
  required: true,
  default: {
    '@path': '$.timestamp'
  }
}

export const user_id: InputField = {
  label: 'User ID',
  description:
    'Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.',
  type: 'string',
  required: false,
  default: {
    '@path': '$.userId'
  }
}

export const session_id: InputField = {
  label: 'User ID',
  description:
    'Identifier for tracking users regardless of sign-in status. The length should not exceed 128 characters.',
  type: 'string',
  required: false,
  default: {
    '@path': '$.anonymousId'
  }
}

export const resolved_bid_id: InputField = {
  label: 'Resolved Bid ID',
  description:
    'Identifier of an instance of a resolved auction for a determined product. The length should not exceed 128 characters.',
  type: 'string',
  required: false,
  default: {
    '@path': '$.resolvedBidId'
  }
}
